--- 
general: 
  pipeline: sap-cloud-sdk
  projectName: cloud-cap-s4ems-bp
  unsafeMode: false
stages: 
  Release: 
    cloudFoundryDeploy: true
steps: 
  artifactPrepareVersion: 
    buildTool: mta
    dockerImage: "s4sdk/docker-node-browsers:v15"
    npmExecute: ~
  cloudFoundryDeploy: 
    cloudFoundry: 
      apiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
      credentialsId: cloud
      org: sfmissionorg
      space: dev
    mtaDeployParameters: "-f --version-rule ALL"
  mtaBuild: 
    mtaBuildTool: cloudMbt
